qqUin:
qqPasswd:
# 1:安卓手机(默认) 2:aPad 3:安卓手表 4:MacOS 5:iPad
protocol: 1
tgToken:
mongoDb:
  connStr: mongodb://localhost
  dbName: q2tg
crv:
  host:
  token:
api:
  enabled: false
  port: 8080
  deleteNotifier: /deleteMessages
groups:
  - qq:
    tg:
  - qq:
    tg:
cos:
  enabled: false
  secretId:
  secretKey:
  bucket: xxxxxx-1234567890
  region: ap-xxxxxx
  url: https://xxxxxx-1234567890.cos.ap-xxxxxx.myqcloud.com # 不要带末尾的 /
