version: "3.8"
services:
  db:
    image : mongo
    container_name: mongodb_q2tg
    volumes:
      - mongodb_q2tg:/data/db
    restart: unless-stopped
  q2tg:
    image: ghcr.io/clansty/q2tg
    container_name: main_q2tg
    environment:
      - |
        Q2TG_CONFIG=
        qqUin: 12345678
        qqPasswd: P@ssw0rd
        # 1:安卓手机(默认) 2:aPad 3:安卓手表 4:MacOS 5:iPad
        protocol: 1
        tgToken: 12345:xxxxxxxxxx
        mongoDb:
          connStr: mongodb://db
          dbName: q2tg
        crv:
          host:
          token:
        api:
          enabled: false
          port: 8080
          deleteNotifier: /deleteMessages
        groups:
          - qq: 1234567
            tg: -100123456789
          - qq: 7654321
            tg: -100987654321
        cos:
          enabled: false
          secretId:
          secretKey:
          bucket: xxxxxx-1234567890
          region: ap-xxxxxx
          url: https://xxxxxx-1234567890.cos.ap-xxxxxx.myqcloud.com # 不要带末尾的 /

    restart: unless-stopped
    depends_on:
      - db

volumes:
  mongodb_q2tg:
